### PR TITLE
Fix Boost version conflicts - works on Noetic

### LINKED ISSUE #4: segmentation faults on 32 bit machines with old boost versions
see discussion here: 
http://answers.ros.org/question/190902/two-versions-of-libboost/

### LINKED ISSUE #6: Exception 'boost::thread_interrupted'
Thanks for the node! We are having some exception thrown every randomly 20% of the time we are using the node.

Background info:
- Ubuntu 12.04
- ROS Hydro
- Boost version: 1.46.1.7

Trace:

[ INFO] [1417737946.520509880]: setting up grab_vicon_pose service server ... 
[ INFO] [1417737946.522555280]: setting up segment calibration service server ... 
[ WARN] [1417737946.525454880]: grab frame returned false
terminate called after throwing an instance of 'boost::thread_interrupted'
[vicon-2] process has died [pid 25573, exit code -6, cmd /home/asrl/banff/utias/devel/lib/vicon_bridge/vicon_bridge __name:=vicon __log:=/home/asrl/.ros/log/7549afc2-7c12-11e4-93a3-f81edfde4c6d/vicon-2.log].
log file: /home/asrl/.ros/log/7549afc2-7c12-11e4-93a3-f81edfde4c6d/vicon-2*.log

### LINKED ISSUE #13: Not compiling on odroid u3
Hello,
I have been trying to get the package working on my system, however its not working. I am not able to catkin_make it successfully. Im using ROS indigo. 

This is the error i keep getting. HELP PLEASE!!

```
Scanning dependencies of target vicon_bridge_generate_messages_cpp
[ 60%] Generating C++ code from vicon_bridge/Markers.msg
[ 62%] Built target msf_core
Scanning dependencies of target vicon_bridge_generate_messages_py
[ 63%] Generating Python from MSG vicon_bridge/Markers
Linking CXX executable /home/odroid/indigo_ws/devel/lib/vicon_bridge/testclient
/usr/bin/ld.bfd.real: skipping incompatible /home/odroid/indigo_ws/src/vicon_bridge/vicon_sdk/Vicon_SDK_1.3_Linux/32-bit/libViconDataStreamSDK_CPP.so when searching for -lViconDataStreamSDK_CPP
/usr/bin/ld.bfd.real: cannot find -lViconDataStreamSDK_CPP
collect2: error: ld returned 1 exit status
make[2]: *** [/home/odroid/indigo_ws/devel/lib/vicon_bridge/testclient] Error 1
make[1]: *** [vicon_bridge/CMakeFiles/testclient.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Thanks

### LINKED ISSUE #19: could not build on ubuntu-mate 16.04
Hello.
I am trying to build vicon_bridge from catkin_ws on ubuntu-mate 16.04 installed on raspberry pi 3. The procedure that  I followed for the build is,
1- Download ViconDataStreamSDK from company website to /home/pi/Documents/.
2- Download vicon_bridge from this repository to catkin_ws/src.
3- Set the library path as, 
export LD_LIBRARY_PATH=/home/pi/Documents/ViconDataStreamSDK_1.7.1_96542h/Linux32-boost-1.55.0/20170125_96542h.x86/:$LD_LIBRARY_PATH 
4- catkin build

However, I am geting a build error as,

Errors     << vicon_bridge:make /home/pi/catkin_ws/logs/vicon_bridge/build.make.010.log
make[2]: *** No rule to make target '/usr/bin/libViconDataStreamSDK_CPP.so', needed by '/home/pi/catkin_ws/devel/.private/vicon_bridge/lib/vicon_bridge/testclient'.  Stop.
make[1]: *** [CMakeFiles/testclient.dir/all] Error 2
make: *** [all] Error 2
cd /home/pi/catkin_ws/build/vicon_bridge; catkin build --get-env vicon_bridge | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << vicon_bridge:make           [ Exited with code 2 ]               
Failed    <<< vicon_bridge                [ 3.0 seconds ]                      
[build] Summary: 0 of 1 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 3.1 seconds total.

catkin_make is also not working. Can someone help me? 

Thank you so much.

### LINKED ISSUE #25: Can not install on the ubuntu 16.04
Anyone have a solution?

### LINKED ISSUE #27: Running on Noetic
I am running Ubuntu 20, ROS noetic, and the node fails to run.

I found that the issue is in `vicon_bridge.cpp`, line 534: 
`tf_broadcaster_.sendTransform(transforms);`

I haven't taken the time to learn about TF, but I know that with this line commented out, it looks like I am getting a pretty good output from the Vicon system.

1) What am I missing with this line commented out?

2) Would moving to tf2 fix this for Noetic?

Thanks!

### LINKED ISSUE #28: Segmentation fault on Ubuntu 20.04 with ROS Noetic
Hi! I am trying to run `roslaunch vicon_bridge vicon.launch` on Ubuntu 20.04 with ROS Noetic, but the process dies soon after connecting to the VICON server. Below is the information output by using `gdb`. Is anyone running into a similar issue? Thanks!

```
(gdb) run
Starting program: /home/henrique/catkin_ws/devel/lib/vicon_bridge/vicon_bridge __name:=vicon __log:=/home/henrique/.ros/log/814fc820-8d8a-11eb-bf20-6922279961a7/vicon-2.log
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4331700 (LWP 36938)]
[New Thread 0x7ffff3b30700 (LWP 36939)]
[New Thread 0x7ffff332f700 (LWP 36940)]
[New Thread 0x7ffff2b2e700 (LWP 36941)]
[New Thread 0x7ffff232d700 (LWP 36942)]
[ INFO] [1616691315.885458948]: Connecting to Vicon DataStream SDK at vicon:801 ...
[New Thread 0x7ffff1b2c700 (LWP 36943)]
[ INFO] [1616691315.886954747]: .
[ INFO] [1616691316.887277343]: ... connected!
[ INFO] [1616691316.887327717]: Setting Stream Mode to ClientPull: Success
[ INFO] [1616691316.887378140]: Axis Mapping: X-Forward Y-Left Z-Up
[ INFO] [1616691316.887389120]: Version: 1.3.0
[ INFO] [1616691316.887397639]: setting up grab_vicon_pose service server ... 
[ INFO] [1616691316.888402378]: setting up segment calibration service server ... 
[ WARN] [1616691316.889472326]: grab frame returned false

Thread 1 "vicon_bridge" received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x110) at ../nptl/pthread_mutex_lock.c:67
67      ../nptl/pthread_mutex_lock.c: No such file or directory.


(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x110) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007ffff7be2fa8 in ros::Publication::hasSubscribers() () from /opt/ros/noetic/lib/libroscpp.so
#2  0x00007ffff7bd31ce in ros::TopicManager::publish(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<ros::SerializedMessage ()> const&, ros::SerializedMessage&) () from /opt/ros/noetic/lib/libroscpp.so
#3  0x00007ffff7bc7046 in ros::Publisher::publish(boost::function<ros::SerializedMessage ()> const&, ros::SerializedMessage&) const () from /opt/ros/noetic/lib/libroscpp.so
#4  0x00007ffff7039260 in tf2_ros::TransformBroadcaster::sendTransform(std::vector<geometry_msgs::TransformStamped_<std::allocator<void> >, std::allocator<geometry_msgs::TransformStamped_<std::allocator<void> > > > const&) () from /opt/ros/noetic/lib/libtf2_ros.so
#5  0x00007ffff7cb6a1b in tf::TransformBroadcaster::sendTransform(std::vector<tf::StampedTransform, std::allocator<tf::StampedTransform> > const&) () from /opt/ros/noetic/lib/libtf.so
#6  0x0000555555587bbf in ViconReceiver::process_subjects(ros::Time const&) ()
#7  0x0000555555588be1 in ViconReceiver::process_frame() ()
#8  0x000055555558c364 in ViconReceiver::grabThread() ()
#9  0x000055555558d6e7 in ViconReceiver::ViconReceiver() ()
#10 0x0000555555573bc4 in main ()
```

### PR DESCRIPTION
**Pull request by wxmerkt**
This PR resolves the issues arising from clashing versions of Boost packaged in different versions of the SDK. To circumvent issues arising from even the latest SDK version on 20.04, this PR builds the libraries from source. The source is included from the manufacturer (https://www.vicon.com/software/datastream-sdk/) and is released under the MIT license.

Supersedes #23 
Resolves #4
Resolves #6
Resolves #13
Resolves #19
Resolves #25
Resolves #27
Resolves #28

### CODE REVIEW

**Comment by ferrolho** [comment]
Thank you so much for this! I can confirm this is working on Ubuntu 20.04, and it solved my issue (#28). It is great to have the latest Vicon SDK too. :tada:

**Comment by ferrolho** [comment]
Hi @markusachtelik, is there any chance you can merge this? Or, who would be the right person to talk to? Many thanks!

**Comment by alexmillane** [comment]
@michaelpantic I don't think we're using this package are we? I.e. there's no easy way of testing these changes with our MAVs?

Given that it seems to solve **a lot** of issues. I'll just merge it in 24h unless anyone at ASL has complaints and/or an easy way of testing the changes.

@wxmerkt @ferrolho Thanks for this 👍

**Comment by michaelpantic** [comment]
@alexmillane No I don't think we ever used this in the last years ( or at least I am not aware)

Agree with the "just" merge strategy!

**Comment by ferrolho** [comment]
I am curious: what you are using instead of this? I am asking because I recently had to get some data off of Vicon for the first time for my project, and from a quick search and chat with my colleagues `vicon_bridge` seems to be the go-to solution. It seems many people use this, so it would be good to merge this PR to update it and solve all the issues mentioned above. But if you no longer use this, it would also be good to know if you are using a better solution for the same problem. Thanks!

**Comment by alexmillane** [comment]
We're using Vicon Tracker + [vrpn_catkin](https://github.com/ethz-asl/vrpn_catkin) + [ros_vrpn_client](https://github.com/ethz-asl/ros_vrpn_client)

Honestly not sure what (if any) advantages our solution has because I've never used vicon_bridge. I guess we must have switched before I arrived in the lab...

**Comment by lukasfro** [comment]
Thanks a lot for the update, helped us out tremendously! However, I still needed an additional change to get it working: when compiling the Vicon SDK, the boost::date_time library could not be found. Apparently, one need to link to it explicitly (see [here](https://stackoverflow.com/questions/17477177/undefined-reference-to-boostgregoriangreg-monthas-short-string-const) ). The following fix in `CMakeLists.txt` did it for me:

`find_package(Boost REQUIRED COMPONENTS thread date_time)`

**Comment by alexmillane** [comment]
@lukasfro I just merged this (I had forgotten). If someone wants to make a separate PR for the change you suggest, they should do that.

**Comment by lukasfro** [comment]
@alexmillane Alright, thanks. I'll make a separate PR.

**Pull request merged**
