### PR TITLE
Fix compilation on 16.04 and add install targets

### PR DESCRIPTION
**Pull request by wxmerkt**
This PR includes commits to fix compilation on ROS Kinetic as well as add install targets. The install targets in this PR use catkin variables in contrast to #36

### CODE REVIEW

**Comment by wxmerkt** [comment]
@alexmillane Any thoughts on this PR? Merging this PR would also resolve #20 and #36

**Comment by alexmillane** [comment]
Looks reasonable to me. Honestly confusing those lines weren't in the CMakelists alread. I've never used this package but I think it makes sense to merge this given #20 and #36.

You think it's good to go?

**Comment by wxmerkt** [comment]
Yes it's good to go - tested it on hardware just now

**Comment by alexmillane** [comment]
Cheers Wolfgang. Merging now :)

**Pull request merged**
